// Builds supabase/seed.sql from scripts/legacy-perfumes.json — the hand-verified
// fragrances that used to be hardcoded in src/perfume-intelligence.jsx.
// Every row is tagged source = 'manual_verified'. Safe to re-run: existing slugs are skipped.
//
//   node scripts/generate-seed.mjs

import { readFileSync, writeFileSync } from "node:fs";

const perfumes = JSON.parse(readFileSync(new URL("./legacy-perfumes.json", import.meta.url), "utf8"));
const TIERS = ["top", "heart", "base"];

const slugify = (s) =>
  s.toLowerCase().normalize("NFKD").replace(/[̀-ͯ]/g, "")
    .replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const lit = (v) => (v === null || v === undefined ? "NULL" : typeof v === "number" ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const arr = (xs) => `ARRAY[${xs.map(lit).join(", ")}]::text[]`;
const values = (rows) => rows.map((r) => `  (${r.join(", ")})`).join(",\n");

const brands = new Map();
const notes = new Map();
for (const p of perfumes) {
  brands.set(slugify(p.brand), p.brand);
  for (const t of TIERS) for (const n of p.notes[t]) notes.set(slugify(n), n);
}

const fragranceRows = perfumes.map((p) => [
  lit(p.id), lit(p.name), lit(slugify(p.brand)), lit(p.year), lit(p.concentration), lit(p.gender),
  lit(p.family), arr(p.subfamilies), lit(p.longevity), lit(p.projection), lit(p.priceTier),
]);
const noteRows = perfumes.flatMap((p) =>
  TIERS.flatMap((t) => p.notes[t].map((n, i) => [lit(p.id), lit(slugify(n)), lit(t), i]))
);
const accordRows = perfumes.flatMap((p) => p.accords.map((a, i) => [lit(p.id), lit(a.name), a.strength, i]));

const sql = `-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.
-- ${perfumes.length} hand-verified fragrances migrated from the old PERFUMES array.
-- Run after supabase/migrations/20260916000000_schema.sql.

BEGIN;

INSERT INTO brands (slug, name) VALUES
${values([...brands].map(([s, n]) => [lit(s), lit(n)]))}
ON CONFLICT (slug) DO NOTHING;

INSERT INTO notes (slug, name) VALUES
${values([...notes].map(([s, n]) => [lit(s), lit(n)]))}
ON CONFLICT (slug) DO NOTHING;

-- Rows are inserted in the original array order, which the app uses as its tie-break.
INSERT INTO fragrances (slug, name, brand_id, year, concentration, gender, family, subfamilies, longevity, projection, price_tier, source)
SELECT v.slug, v.name, b.id, v.year, v.concentration, v.gender, v.family, v.subfamilies, v.longevity, v.projection, v.price_tier, 'manual_verified'
FROM (VALUES
${values(fragranceRows.map((r, i) => [...r, i]))}
) AS v(slug, name, brand_slug, year, concentration, gender, family, subfamilies, longevity, projection, price_tier, ord)
JOIN brands b ON b.slug = v.brand_slug
ORDER BY v.ord
ON CONFLICT (slug) DO NOTHING;

INSERT INTO fragrance_notes (fragrance_id, note_id, tier, position)
SELECT f.id, n.id, v.tier, v.position
FROM (VALUES
${values(noteRows)}
) AS v(fragrance_slug, note_slug, tier, position)
JOIN fragrances f ON f.slug = v.fragrance_slug
JOIN notes n ON n.slug = v.note_slug
ON CONFLICT DO NOTHING;

INSERT INTO fragrance_accords (fragrance_id, accord_name, strength, position)
SELECT f.id, v.accord_name, v.strength, v.position
FROM (VALUES
${values(accordRows)}
) AS v(fragrance_slug, accord_name, strength, position)
JOIN fragrances f ON f.slug = v.fragrance_slug
ON CONFLICT DO NOTHING;

COMMIT;

-- Expected: ${perfumes.length} fragrances, ${brands.size} brands, ${notes.size} notes, ${noteRows.length} fragrance_notes, ${accordRows.length} fragrance_accords
SELECT
  (SELECT count(*) FROM fragrances WHERE source = 'manual_verified') AS fragrances,
  (SELECT count(*) FROM brands) AS brands,
  (SELECT count(*) FROM notes) AS notes,
  (SELECT count(*) FROM fragrance_notes) AS fragrance_notes,
  (SELECT count(*) FROM fragrance_accords) AS fragrance_accords;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`seed.sql: ${perfumes.length} fragrances, ${brands.size} brands, ${notes.size} notes, ${noteRows.length} note links, ${accordRows.length} accords`);
